### PR TITLE
add new screenshots

### PR DESCRIPTION
**Pull request by tutebatti**
as requested by @mfranke93 in #138

### CODE REVIEW

**Comment by mfranke93** [comment]
I'm still not 100% happy with the new versions. Especially seeing them side by side with the replaced images, it is quite obvious that the map glyphs are much smaller in the new brushing and linking screenshots, and the gaps in the religion hierarchy much larger. I will add my own suggestion for you to approve.

**Comment by tutebatti** [comment]
> Especially seeing them side by side with the replaced images, it is quite obvious that the map glyphs are much smaller in the new brushing and linking screenshots

This is correct. When making the screenshots it seemed to me as if my visualization skips the zoom level you apparently had. Or does the zoom level also depend on screen resolution? I have tried the "+" and "-" keys on my keyboard, the buttons in the visualization as well as my mouse wheel.

> and the gaps in the religion hierarchy much larger

Sorry, didn't think that would be a problem.

**Comment by mfranke93** [comment]
> This is correct. When making the screenshots it seemed to me as if my visualization skips the zoom level you apparently had. Or does the zoom level also depend on screen resolution? I have tried the "+" and "-" keys on my keyboard, the buttons in the visualization as well as my mouse wheel.

The glyph size does not depend on zoom level. I did the screenshot with some browser zoom (150% I think), because screenshots are generally shown in smaller size. See my latest commit.

**Comment by tutebatti** [comment]
This does, in fact, look better. I hadn't thought about browser zoom. :see_no_evil:

**Comment by mfranke93** [comment]
@tutebatti I changed the three images. If you have no objections, I would merge this.

**Comment by tutebatti** [comment]
Please do! And thanks!

**Pull request merged**
