### PR TITLE
add new screenshots

### PR DESCRIPTION
**Pull request by tutebatti**
If minor differences in resolution and content (timeline mode in full-visualization) are ok, we would be good to go with this.

### CODE REVIEW

**Review by mfranke93 — CHANGES_REQUESTED** [review]
The religion hierarchy screenshots are too tall now, and the gaps look suboptimal. Please change those.

**Comment by mfranke93** [comment]
We do not merge feature branches into `main` directly. Also, it would make sense to replace the screenshots from the start page as well while you're at it. So, I am going to close this, and ask you to make a new PR as follows:

 1. Of a branch that is up-to-date with `release/v1.1.3`
 2. PR *back onto* `release/v1.1.3`
 3. Including the screenshots of the start page that should change
 4. With the religion hierarchy screenshots as detailed above (same layout as before the PR)

**Comment by tutebatti** [comment]
Will do. However, I do not see any need for new screenshots for the start page. Map material is the same. No Shiite sub groups shown. Do you see anything there?

**Comment by mfranke93** [comment]
> Do you see anything there?

No, sorry. I thought that had a full screenshot, but in fact the Shi'ite subgroups are not visible (barely) in the partial one. So scratch that.

**Pull request closed without merging**
